### ISSUE TITLE
Unsatisfied link error: no gluegen-rt in java.library.path

### ISSUE THREAD

**Issue by metasim** [retronym/jzy3d-demo#1]
Just checked out the code and ran `sbt run`.  On Mac OS X 10.8.4, sbt version 0.12.3, Scala 2.10.2.

Here's the output I get:

```
 sbt run
[info] Loading global plugins from /Users/xxx/.sbt/plugins
[info] Loading project definition from /Users/xxx/Coding/libs/jzy3d-demo/project
[info] Set current project to jzy-demo (in build file:/Users/xxx/Coding/libs/jzy3d-demo/)

Multiple main classes detected, select one to run:

 [1] org.jzy3d.demos.surface.MexicanDemo
 [2] org.jzy3d.demos.surface.ColorWaveDemo
 [3] org.jzy3d.demos.surface.BuildSurfaceDemo
 [4] org.jzy3d.demos.surface.WireSurfaceDemo

Enter number: 2

[info] Running org.jzy3d.demos.surface.ColorWaveDemo 
[error] (run-main) java.lang.UnsatisfiedLinkError: no gluegen-rt in java.library.path
java.lang.UnsatisfiedLinkError: no gluegen-rt in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
    at java.lang.Runtime.loadLibrary0(Runtime.java:845)
    at java.lang.System.loadLibrary(System.java:1084)
    at com.jogamp.gluegen.runtime.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:102)
    at com.jogamp.gluegen.runtime.NativeLibLoader.access$000(NativeLibLoader.java:51)
    at com.jogamp.gluegen.runtime.NativeLibLoader$1.run(NativeLibLoader.java:70)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.jogamp.gluegen.runtime.NativeLibLoader.loadGlueGenRT(NativeLibLoader.java:68)
    at com.jogamp.common.jvm.JVMUtil.<clinit>(JVMUtil.java:56)
    at javax.media.opengl.GLProfile.<clinit>(GLProfile.java:1141)
    at org.jzy3d.global.Settings.<init>(Settings.java:53)
    at org.jzy3d.global.Settings.getInstance(Settings.java:18)
    at org.jzy3d.demos.Launcher$.openDemo(Launcher.scala:19)
    at org.jzy3d.demos.Launcher$.openDemo(Launcher.scala:15)
    at org.jzy3d.demos.surface.ColorWaveDemo$.main(ColorWaveDemo.scala:19)
    at org.jzy3d.demos.surface.ColorWaveDemo.main(ColorWaveDemo.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 3 s, completed Jul 23, 2013 2:47:41 PM

```

**Comment by jzy3d** [comment]
This might help you: http://jzy3d.org/troubleshooting.php
Otherwise try to get the library from maven if sbt is not configured to do so: https://github.com/jzy3d/jzy3d-tutorials/blob/master/pom.xml
